### ISSUE TITLE
"FFTmodelv1.hdf5" file signature not found

### ISSUE THREAD

**Issue by li-bai-hub** [ganyguru/TEMGUILESC#1]
The "FFTmodelv1.hdf5" file is damaged and causes the program crashed.
The error is as following:
```
Traceback (most recent call last):
  File "/root/TEMGUILESC/GUI_Final.py", line 116, in <module>
    model.load_weights(resourcePath('FFTmodelv1.hdf5'))
  File "/root/code/TEMGUILESC/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/code/TEMGUILESC/.venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/root/code/TEMGUILESC/.venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
```
We have tried to examine the  "FFTmodelv1.hdf5" file directly, the results was:
```
# h5dump FFTmodelv1.hdf5 
h5dump error: unable to open file "FFTmodelv1.hdf5"
```

Hope you upload the benign "FFTmodelv1.hdf5" as soon as possible!

**Comment by ganyguru** [comment]
Updated the hdf5 file
